### PR TITLE
Add editor opening.

### PR DESCRIPTION
**Pull request by dereuromark**
Can someone verify this works?
I couldnt get it work with my PHPStorm, but maybe I missed something?

### CODE REVIEW

**Comment by ypnos-web** [comment]
This works great. I would love this to be merged.

I have two suggestions:
- Mention in the README the mechanism this is using (`phpstorm://` URL). On some systems you need to install additional software to make phpstorm URLs work.
- Use `Error.editor` (or find a better name) instead of `Whoops.editor` in configuration hash.

**Comment by dereuromark** [comment]
@jadb If you are not maintaining it anymore feel free to sign it over.

**Comment by dereuromark** [comment]
@ADmad Do you know if anyone is still maintaining it? Looks pretty dead and someone should take over then now.

**Comment by ADmad** [comment]
To the best of my knowledge no one besides jadb has access to the gourmet repos. I too haven't had any contact with him in quite a while.

**Comment by phillaf** [comment]
I confirm

**Comment by dereuromark** [comment]
OK.. I will close this then as this repo seems unmaintained.

I moved all my improvements into a released package: https://github.com/dereuromark/cakephp-whoops

All browser and OS related tips are in the https://github.com/dereuromark/cakephp-whoops/wiki section for everyone to bring in his own experiences and share the solutions here.

@ypnos-web I added your suggestions to the docs.

If people could provide small screencasts of how it looks and works in their OS systems, that would be awesome. I can link them then in the readme and wiki sections as well.
Thanks guys!

**Pull request closed without merging**
